[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/DHT sensor library@^1.4.7
	bblanchon/ArduinoJson@^7.2.2
	vshymanskyy/TinyGSM@^0.12.0
monitor_speed = 115200
